name: fast_cached_network_image
description: A flutter package to cache network image fastly without any native dependencies.You can add beautiful loaders, percentage indicators and error builder.
version: 1.2.0
publish_to: none
homepage: https://github.com/CHRISTOPANANJICKAL/fast_cached_network_image
repository: https://github.com/CHRISTOPANANJICKAL/fast_cached_network_image
issue_tracker: https://github.com/CHRISTOPANANJICKAL/fast_cached_network_image/issues

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.3.3
  isar: ^3.1.0+1
  isar_flutter_libs:
    git: https://github.com/kumsumit/isar_flutter_libs.git
  path_provider:
    git: https://github.com/kumsumit/path_provider.git
  uuid: ^4.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 
    git: https://github.com/kumsumit/flutter_lints.git
  isar_generator:
    git: https://github.com/kumsumit/isar_generator.git
  build_runner: ^2.4.6 
